### ISSUE TITLE
✨ Feat: 할 일 카드 생성 모달 컴포넌트

### ISSUE THREAD

**Issue by oceanlee-seoul** [Part3-Team15/taskify#11]
# 작업 설명

할 일 카드 생성 모달 컴포넌트
<img width="278" alt="스크린샷 2024-06-21 오전 10 35 23" src="https://github.com/Part3-Team15/taskify/assets/108586797/eb06d2da-2135-4832-8a5e-50d08236592a">
API 
- (POST)baseURL/{teamId}/cards
- (GET)baseURL/{teamId}/members
*담당자 선정을 위한 Member 조회

state : 카드 상세 정보

## 세부 작업 목록

- [x] input validation
- [x] API Test
- [x] 퍼블리싱 - 태그 컬러 지정

### 선행 이슈 
- [x] 유저 기능

**Comment by un0211** [comment]
여기서 태그 생성시 컬러 지정하는 함수 같이 만들거나 아니면 함수를 위한 이슈 하나 만들거나 해야겠네요

**Comment by oceanlee-seoul** [comment]
> 여기서 태그 생성시 컬러 지정하는 함수 같이 만들거나 아니면 함수를 위한 이슈 하나 만들거나 해야겠네요

맞습니다!! 논의할 게 좀 있을 것 같아서 이슈로 추가하는게 좋을 것 같네요!
