### ISSUE TITLE
🐛 Bug: 디자인 수정사항

### ISSUE THREAD

**Issue by un0211** [Part3-Team15/taskify#171]
# 🐛 버그 설명

디자인 관련 문제들 모아 놨다가 한번에 처리합시다!
생길때마다 이어서 작성해 주시면 됩니다!

## 대시보드
- [x] 페이지 크기 문제

https://github.com/Part3-Team15/taskify/assets/24778465/48dfc14d-8b8d-42a9-9664-a5f0e986e5ae

대시보드에서만 특이하게 페이지가 옆으로 더 생깁니다! 아마 스크롤 관련 문제일 것 같은데..

- [x] 작은 크기에서 찌그러짐

<img width="327" alt="image" src="https://github.com/Part3-Team15/taskify/assets/24778465/c6e691fa-46dd-444f-8306-034218b83966">

## 내 대시보드

- [x] 그림 세로 가운데로

<img width="783" alt="image" src="https://github.com/Part3-Team15/taskify/assets/24778465/98819799-d1d2-4ad1-9ee8-de20c05d3682">

- [x] 버튼 크기 문제
<img width="400" alt="image" src="https://github.com/Part3-Team15/taskify/assets/24778465/11562e7b-2016-44d6-ace3-4e8e585e61cd" />

### 구성원

- [x] 아직도 구성원 너비 문제..
<img width="275" alt="image" src="https://github.com/Part3-Team15/taskify/assets/24778465/6f26a2f2-cf8c-4f71-80b5-1420d8e9ebb6">

### 드롭다운
- [x] 작은크기에서 위치 문제

https://github.com/Part3-Team15/taskify/assets/24778465/c67863d9-5675-404d-ae13-e2da5316d4b8

드롭다운 페이지에 대해 absolute로 되어있어서 작은 크기에서 위치가 이상해집니다.
header를 relative로 바꾸면 바로 해결될 것 같아요! (고친다는 게 딴짓하다가 머지해버렸네요 ㅠ)

- [x] z-index 조절
<img width="154" alt="image" src="https://github.com/Part3-Team15/taskify/assets/24778465/45e73389-d77d-49a9-a058-ecf08c405aaf">

## 랜딩페이지

- [x] 기존 요구사항과 바뀐 부분 반영
<img width="275" src="https://github.com/Part3-Team15/taskify/assets/24778465/c40c8a14-a649-413d-8a5e-da28702f3420" />

**Comment by wayandway** [comment]
<img width="563" alt="스크린샷 2024-07-02 오후 3 37 06" src="https://github.com/Part3-Team15/taskify/assets/64190056/2e43931e-f787-4e04-9ba1-a19c2b4cdf5a">

- 헤더 "관리", "초대하기" 버튼이 아이폰 일부 모델에서 깨지는 문제
(이것도 모바일에서는 아이콘모양으로 바꾸는 등 수정하면 좋을 것 같습니다!)

**Comment by un0211** [comment]
- #169
여기서 깨지는 문제는 해결해두었는데, 아직 PR 안닫아서 아이콘으로 바꾸는 작업은 지금 바로 할게요~~

**Comment by wayandway** [comment]
대시보드 스크롤 아직 미세하게 조금 남아있더라구요😱
수정 하겠습니다..!!

**Comment by un0211** [comment]
<img width="531" alt="image" src="https://github.com/Part3-Team15/taskify/assets/24778465/4b20bd87-da1f-40ed-9487-40693f326053">

내 대시보드도 모바일에서 작게 고정보다는 100% 차는게 예쁠 것 같아요

**Comment by wjsdncl** [comment]
수정하겠습니다! 🫡

**Comment by wjsdncl** [comment]
내 페이지도 짤려서 수정하겠습니다!
![image](https://github.com/Part3-Team15/taskify/assets/89517903/db01d9a3-0d58-4adb-833d-778a050cbc0c)

**Comment by un0211** [comment]
<img width="201" alt="image" src="https://github.com/Part3-Team15/taskify/assets/24778465/eeecb45a-9d32-49bd-b56a-94f72f72ee6d">

지윤님 이제 머지되었으니 여기에 올릴게요!
이름 긴 경우가 아직도 깨집니다. (editCardModal 브랜치인데, 최신변경이 반영되었는지는 모르겠어요)
알람 뜨게 댓그로 남깁니다.

**Comment by wayandway** [comment]
> * [x]  담당자 닉네임 긴 경우 레이아웃 깨짐
> 

> 
> * [x]  이름이 길어지면 버튼이 작아짐
> 


> 
> * [x]  댓글에서 유저 아이콘 찌그러짐
> 


수정했습니다!
