### ISSUE TITLE
🐛 Bug: 대시보드 카드 목록 새로고침이 안됨

### ISSUE THREAD

**Issue by un0211** [Part3-Team15/taskify#182]
# 🐛 버그 설명

현재 대시보드 내 컬럼은 useQuery(useFetchData)로 queryKey를 등록해 불러오지만,
그 안에 있는 카드는 그냥 컬럼 목록이 바뀔때마다 get으로 불러오고 있습니다.
카드 생성 시 카드 정보도 바로 반영하려면 카드도 useQuery(useFetchData)로 불러와야 할 것 같습니다!

## 상황

현재 코드

https://github.com/Part3-Team15/taskify/blob/5203abcd104af14ec914b3b40584f1c31b72cca1/src/containers/dashboard/ColumnsSection.tsx#L20
```
  const {
    data: columns,
    isLoading,
    error,
  } = useFetchData<ColumnsResponse>(['columns', id], () => getColumnsList(Number(id)));
  const columnList = columns?.data;

  const [cardLists, setCardLists] = useState<Record<number, CardType[]>>({});

  useEffect(() => {
    if (columnList) {
      columnList.forEach((column) => {
        const fetchCards = async () => {
          const { data } = await getCardsList(column.id);
          setCardLists((prev) => ({ ...prev, [column.id]: data.cards }));
        };
        fetchCards();
      });
    }
  }, [columnList]);

```

카드 변화를 반영할 수 없음

https://github.com/Part3-Team15/taskify/assets/24778465/fb302714-e9c4-4ee1-afcd-3a979927d9dd

## 코멘트

- 카드 정보는 각 컬럼에서 useFetchData를 이용해 받아오면 좋을 듯 합니다.
- 다른 사람이 수정한 경우에도 바로 볼 수 있게, 2-3초마다 새로고침 되게 하면 좋을 것 같습니다!

**Comment by wayandway** [comment]
버그리포트 감사합니다 🙇‍♂️ 이 이슈는 제가 맡겠습니다!
이 부분은 제가 SSR 적용하면서 건드려야 될 것 같아요!!
