### ISSUE TITLE
✨ Feat: 사이드바 대시보드 즐겨찾기

### ISSUE THREAD

**Issue by wjsdncl** [Part3-Team15/taskify#188]
## 작업 설명

간단한 Next.js 서버를 만들어서 즐겨찾기 만들기

### API

- next.js API 만들기

## 세부 작업 목록

- [x] API 제작
- [x] API 연동
- [x] 사이드바에 즐겨찾기 추가

**Comment by un0211** [comment]
요건 추가한다면 나의 대시보드에서도 즐겨찾기 먼저 보여주면 되겠어요~~
