### ISSUE TITLE
🐛 Bug: 초대 알림이 새로운 초대만 오는게 아닌 모든 초대가 옴

### ISSUE THREAD

**Issue by wjsdncl** [Part3-Team15/taskify#198]
# 🐛 버그 설명

초대 인원 리스트가 변경되면 초대 리스트의 모든 초대가 옵니다

## 상황

초대 수락, 거절

## 코멘트 (optional)

아까 멘토님에게 시연할때 나타났었습니다.

**Comment by un0211** [comment]
수정해 볼게요~~
