### ISSUE TITLE
✨ Feat: 태그 생성시 컬러 부여 기능 util

### ISSUE THREAD

**Issue by oceanlee-seoul** [Part3-Team15/taskify#26]
# 작업 설명
tag string 값에 따른 color 매칭 로직 util 구현

**카드 컴포넌트** #19 
<img width="213" alt="스크린샷 2024-06-21 오후 1 08 56" src="https://github.com/Part3-Team15/taskify/assets/108586797/9db751f7-362e-4216-b5aa-f1c38d4c4558">
<br>
**카드 상세보기 모달 컴포넌트** #3 
<img width="334" alt="스크린샷 2024-06-21 오후 1 08 40" src="https://github.com/Part3-Team15/taskify/assets/108586797/39b963c9-4447-4863-91ff-9f530afc3a8c">
<br>
**카드 생성 및 수정 컴포넌트** #11 #18 
<img width="355" alt="스크린샷 2024-06-21 오후 1 09 11" src="https://github.com/Part3-Team15/taskify/assets/108586797/1ae273c1-919b-4a0a-8343-105f668f6c3c">

## 세부 작업 목록
태그는 string[]로 전달되기 때문에 컬러 값을 가지고 있을 수 없습니다.
따라서 저희 클라이언트에서 해당 태그 string에 대한 각각의 color를 매칭해주는 로직을 구현 해주어야 할 것 같습니다.
태그에 따라 저희가 지정한 color 중에 랜덤한 color를 줘도 좋을 것 같지만, 
일관성을 위해서 해당 string을 color hex 값으로 매칭하는 것이 좋을 듯 합니다. (근데 그렇게 하면 이쁜 색은 못고를 것 같네요.)

- [ ] tag String 값 컬러 코드로 매칭

## 관련 이슈
#19 
#3 
#11 #18

## 코멘트 (optional)
괜찮은 로직이 있으면 말씀해 주시면 감사하겠습니다!

**Comment by un0211** [comment]
우리가 괜찮은 색상 리스트를 만들고, tagColors: [color1, color2, ...]
태그 string -> idx(0 ... len-1) 매칭하는 함수(tagToIdx)를 만들어 tagColors[idx]로 하면 좋을 것 같습니다. 
해당 함수는
- string -> hex로 변환 -> % tagColors 길이 (마지막 글자일수록 기여도 높을수도)
- string -> 각각의 아스키 합 -> % tagColors 길이
- string -> sha1 등 해시함수 -> % tagColors 길이

등으로 할 수 있을 것 같고, 색이 골고루 배정될지는 알 수 없습니다. 그래도 2, 3은 그나마 랜덤하게 배정될 것 같아요
