### ISSUE TITLE
🐛 Bug: commitlint 규칙때문에 이슈번호 커밋메세지에 추가 거절

### ISSUE THREAD

**Issue by un0211** [Part3-Team15/taskify#51]
# 🐛 버그 설명

`.commitlintrc.ts`에 설정된 규칙때문에 커밋 끝에 이슈번호 붙이는 게 거절당하는 문제가 있습니다.
저희는 'git-commit-emoji'라는 extend를 쓰고 있고, 설정은 [여기](https://github.com/ccnnde/commitlint-config-git-commit-emoji)서 찾아볼 수 있습니다. 
중요한 내용은 아래와 같습니다.
```
<emoji> <type>(<scope>): <subject>
<BLANK LINE>
<body>
<BLANK LINE>
<footer>
```

## 상황

이슈번호를 어떤 형식으로든(`(#1)`, `[#1]`, `#1`) 커밋 메시지 마지막에 붙이면 다음과 같이 에러가 발생합니다.

<img width="402" alt="image" src="https://github.com/Part3-Team15/taskify/assets/24778465/f21e9168-9b51-466e-a359-c215792003fa">

- 제 추측으로는 보통 관련된 이슈를 footer에 적기 때문에 이 규칙을 적용했을 때 제목 끝에 이슈를 달면 footer 취급이 되고, 제목이 없다는 에러가 뜨는 것 같습니다.
- 설정을 유지한 해결 방법으로는 왼쪽 이미지와 같이 scope인 척 하거나, 오른쪽 이미지와 같이 제목과 한 줄 구분지어 적는 방법이 있습니다.
<img width="385" alt="image" src="https://github.com/Part3-Team15/taskify/assets/24778465/ffdfa10c-2407-4a77-9eb8-0040a3e8292e">
<img width="343" alt="image" src="https://github.com/Part3-Team15/taskify/assets/24778465/89b2d881-fb95-444a-bd14-b8db4e27bfdd">

- 팀에서 scope를 적고 있지 않기 때문에, 첫번째 방법이 괜찮을 것 같고, 설정을 변경하는 방법을 찾아볼 수도 있습니다!
- 찾아보니 브랜치 이름에 이슈 번호가 포함된다면 자동으로 커밋에 이슈번호 추가해주는 스크립트 작성하는 분들도 있긴 하네요

## 코멘트

- 읽어보시고 코멘트로 의견 남겨주세요~~

**Comment by wayandway** [comment]
스코프 쓰는 방식에 한 표합니다 ㅎㅎ!
