### ISSUE TITLE
🐛 Bug: 잘못된 요청을 무한히 다시보내는 문제

### ISSUE THREAD

**Issue by un0211** [Part3-Team15/taskify#77]
# 🐛 버그 설명

잘못된 요청이나 권한이 없는 요청이 와서 서버에서 반려하면, 무한히 다시 재요청을 보내는 문제가 있습니다.

## 상황

대시보드 구성원 조회를 하는데, 유저가 권한이 없는 대시보드에 대해 요청을 보내자 무한히 재요청을 보냅니다.
<img width="414" alt="image" src="https://github.com/Part3-Team15/taskify/assets/24778465/7d40db23-bf4d-4147-b279-2880e11c77c1">

## 코멘트 (optional)

코드나 자세한 사항은 하고 있는 작업 마무리하고 추가하겠습니다.

**Comment by wayandway** [comment]
권한 없는 대시보드에선 요청을 아예 할 수 없도록 막아놔야겠네요..
버그 리포트 감사합니다 👍

**Comment by un0211** [comment]
retry: false 으로 설정하니 한 번 실패하면 더 안 갑니다!!
저희 어차피 실패하는 경우는 계속 보낸대도 실패할 확률이 높은데 (대부분 권한 문제)
retry 를 3회 이내로 설정하는 게 어떨까요??
